### ISSUE TITLE
How to get path/to/bert/base/uncased/pt？

### ISSUE THREAD

**Issue by cornliu** [Yifan-Gao/explicit_memory_tracker#2]
In the beginning of the readme, there is a wget to download the bert-base-uncased.tar.gz. Is it the model that we have to enter in the path/to/bert/base/uncased/pt of the end to end task? 
If the bert-base-uncased.tar.gz is in the ./explicit_memory_tracker/pretrained_models/ as the readme, what is the exact instruction we have to run on the end-to-end task?

**Comment by Yifan-Gao** [comment]
I recommend you use the absolute path to the BERT pretrained model. In your case, it should be `absolute/path/to/explicit_memory_tracker/pretrained_models/bert-base-uncased.tar.gz`.

**Comment by cornliu** [comment]
Thank you very much! I think the problem is that I download a damaged file.
